//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Universal_Share.Options {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Universal_Share.Options.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die DialogResult: ähnelt.
        /// </summary>
        internal static string Editor_CreateNewRememberType_DialogResult_ {
            get {
                return ResourceManager.GetString("Editor_CreateNewRememberType_DialogResult_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Extension: ähnelt.
        /// </summary>
        internal static string Editor_CreateNewRememberType_Extension_ {
            get {
                return ResourceManager.GetString("Editor_CreateNewRememberType_Extension_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Base64Token: ähnelt.
        /// </summary>
        internal static string Editor_CreateNewTokenItem_Base64Token_ {
            get {
                return ResourceManager.GetString("Editor_CreateNewTokenItem_Base64Token_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Remember: ähnelt.
        /// </summary>
        internal static string Editor_CreateNewTokenItem_Remember_ {
            get {
                return ResourceManager.GetString("Editor_CreateNewTokenItem_Remember_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Trusted: ähnelt.
        /// </summary>
        internal static string Editor_CreateNewTokenItem_Trusted_ {
            get {
                return ResourceManager.GetString("Editor_CreateNewTokenItem_Trusted_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  (0 or 1) ähnelt.
        /// </summary>
        internal static string Editor_CreateNewTypeHolder___0_or_1_ {
            get {
                return ResourceManager.GetString("Editor_CreateNewTypeHolder___0_or_1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 1 ähnelt.
        /// </summary>
        internal static string Editor_CreateNewTypeHolder__True {
            get {
                return ResourceManager.GetString("Editor_CreateNewTypeHolder__True", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Arguments: ähnelt.
        /// </summary>
        internal static string Editor_CreateNewTypeHolder_Arguments_ {
            get {
                return ResourceManager.GetString("Editor_CreateNewTypeHolder_Arguments_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ArgumentsAfterPathToFile: ähnelt.
        /// </summary>
        internal static string Editor_CreateNewTypeHolder_ArgumentsAfterPathToFile_ {
            get {
                return ResourceManager.GetString("Editor_CreateNewTypeHolder_ArgumentsAfterPathToFile_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ArgumentsBeforePathToFile: ähnelt.
        /// </summary>
        internal static string Editor_CreateNewTypeHolder_ArgumentsBeforePathToFile_ {
            get {
                return ResourceManager.GetString("Editor_CreateNewTypeHolder_ArgumentsBeforePathToFile_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die CloseFileStream: ähnelt.
        /// </summary>
        internal static string Editor_CreateNewTypeHolder_CloseFileStream_ {
            get {
                return ResourceManager.GetString("Editor_CreateNewTypeHolder_CloseFileStream_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Description: ähnelt.
        /// </summary>
        internal static string Editor_CreateNewTypeHolder_Description_ {
            get {
                return ResourceManager.GetString("Editor_CreateNewTypeHolder_Description_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die OpenWith: ähnelt.
        /// </summary>
        internal static string Editor_CreateNewTypeHolder_OpenWith_ {
            get {
                return ResourceManager.GetString("Editor_CreateNewTypeHolder_OpenWith_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die UserConfirm: ähnelt.
        /// </summary>
        internal static string Editor_CreateNewTypeHolder_UserConfirm_ {
            get {
                return ResourceManager.GetString("Editor_CreateNewTypeHolder_UserConfirm_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Paket: id = [{0}], Token(0,8) = [{1}] ähnelt.
        /// </summary>
        internal static string NetBase_PaketAndToaken {
            get {
                return ResourceManager.GetString("NetBase_PaketAndToaken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Remove Reg?
        /// ähnelt.
        /// </summary>
        internal static string ServerForm__RegList_DoubleClick_ {
            get {
                return ResourceManager.GetString("ServerForm__RegList_DoubleClick_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Remove RememberAccess?
        /// ähnelt.
        /// </summary>
        internal static string ServerForm__RememberList_DoubleClick_ {
            get {
                return ResourceManager.GetString("ServerForm__RememberList_DoubleClick_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Remove Token?
        /// ähnelt.
        /// </summary>
        internal static string ServerForm__TokenList_DoubleClick_ {
            get {
                return ResourceManager.GetString("ServerForm__TokenList_DoubleClick_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 
        ///Die Settings Datei Wird Gelöscht... ähnelt.
        /// </summary>
        internal static string XmlLoad_DeleatingFile {
            get {
                return ResourceManager.GetString("XmlLoad_DeleatingFile", resourceCulture);
            }
        }
    }
}
